### ISSUE TITLE
Support for dumping with natural keys

### ISSUE THREAD

**Issue by mvattuone** [semente/django-smuggler#48]
Hi there, thanks for making a supremely useful application.

I was wondering if there was a way to dump data with natural keys, such that I could easily dump my Users model and load it into a clean install without getting 'ContentType matching query does not exist' type errors (i.e. errors for data I don't really need).

Thanks for reading.

**Comment by semente** [comment]
@mvattuone could you double check if the pull request #50 fixes your issue? Thanks.

**Comment by mvattuone** [comment]
Unfortunately the app I had been working on with that issue is no longer
under my control, so I can't.  Sorry!

Mike

**Comment by semente** [comment]
No problem, thanks!
