### ISSUE TITLE
coveralls command is failing

### ISSUE THREAD

**Issue by semente** [semente/django-smuggler#51]
coveralls command is failing and breaking travis-ci build. Based on the command error output I even have added the file https://github.com/semente/django-smuggler/blob/master/.coveralls.yml but with no success, build is still broken.

For reference: https://travis-ci.org/semente/django-smuggler/jobs/93181185

@jaap3, do you have any idea?

**Comment by jaap3** [comment]
I got it working again. You want to invalidate that repo_token from coveralls (if possible) because it's not supposed to be public.

**Comment by jaap3** [comment]
I also made everything work in Django 1.9 and dropped support for Django < 1.7 in accordance with Django's support policy (https://www.djangoproject.com/download/#supported-versions)

**Comment by semente** [comment]
Thank you @jaap3! I put the repo_token following the example of other projects in hope to solve this issue because I was spending too much time to figure out how to solve this. I didn't notice coveralls command must go now in .travis.yml. :)

Token is regenerated. Let me know if you need it to run it locally.
