### ISSUE TITLE
Figure out why coverage is not 100% on Django 1.9

### ISSUE THREAD

**Issue by jaap3** [semente/django-smuggler#52]
We're not hitting these lines in Django 1.9 https://coveralls.io/builds/4274269/source?filename=smuggler%2Fviews.py#L158

Need to find out why and fix it.

**Comment by jaap3** [comment]
Not even sure what that code does, seems like get_fieldsets is not called for one of the admin views. Possibly the one where you can pick files that are stored on the server?

**Comment by semente** [comment]
@jaap3, with my recent changes (b0ef35d), coverage isn't 100% yet, but I will release version 0.7 anyway. :)

**Comment by semente** [comment]
Weird, in my local machine it says it is 99% covered (see the image below)... Well, closing this issue anyway based on coveralls.io.

![2016-02-25_18 25_636x195](https://cloud.githubusercontent.com/assets/29862/13334937/54772bd0-dbed-11e5-840a-00dc06aa1945.png)

**Comment by jaap3** [comment]
Looks good to me, thanks
