### ISSUE TITLE
Django 1.9+ jquery.min.js staticfile

### ISSUE THREAD

**Issue by MaZZly** [semente/django-smuggler#57]
Got an error when using a custom staticfile handler, because it could not find
`/admin/js/jquery.min.js` in the location.

According to https://github.com/django-admin-bootstrap/django-admin-bootstrap/issues/88 the jquery file is from 1.9 onwards in `/admin/js/vendor/jquery/jquery.min.js`

Simple workaround for me now was to copy the file over to old place as well.

But this should probably be fixed from the package itself so that form media is loaded correctly depending on version.

**Comment by jaap3** [comment]
A pull request would be much appreciated. I'd suggest setting the default location to the "new" location and falling back to the old location if `django.VERSION < (1, 9)`

**Comment by jaap3** [comment]
This is no longer relevant

**Comment by darekfrynas** [comment]
@jaap3 this problem still occurs to me in Django 2.1.1
