### ISSUE TITLE
Models with foreign key to auth.user instances can't be loaded correctly

### ISSUE THREAD

**Issue by keks42** [semente/django-smuggler#60]
When dumping the auth data the user ids/primary keys are not dumped, so when loading the file again, other models having ForeignKeys to User instances can't be loaded properly. 
When loading a file with dumped auth data, the users are imported correctly but get new ids/primary keys.

**Comment by jaap3** [comment]
I think this has something to do with the use of natural keys (https://docs.djangoproject.com/en/2.0/topics/serialization/#serialization-of-natural-keys)

Maybe the call to dumpdata isn't correct for your version of Django?

**Comment by keks42** [comment]
It was my fault - you shouldn't use ForeignKeys as a primary key. Doing that ends in not being able to load the dumped data correctly.
