### ISSUE TITLE
Load view not working

### ISSUE THREAD

**Issue by MarioBG** [semente/django-smuggler#64]
I'm running Django 2.2.5 on Python 3.7, and I've noticed that, when trying to open the 'load' view in DEBUG=False, it produces a Server error (500) view; it does, however, function correctly in DEBUG=True. Please, consider looking into this. Thanks a lot.

My settings.py can be found in [here](https://pastebin.com/W67SxH02) and my urls.py is [here](https://pastebin.com/UHRRaX6Q). If you need any more information please reply to the issue.

**Comment by MarioBG** [comment]
Nevermind, turns out the problem was an issue with staticfiles, although it was a bit difficult to diagnose. Nothing wrong on your side, though. Sorry for the inconvenience

**Comment by semente** [comment]
hey, no problem! thank you

**Comment by dev-ritik** [comment]
Hello @MarioBG , I am stuck at the same problem. It looks for a js file.
`ValueError: Missing staticfiles manifest entry for 'admin/js/jquery.init.jsadmin/js/core.js'`
It would be a great help for me and anyone else facing the same issue if you could describe how you fixed it.
Thanks.

**Comment by jaap3** [comment]
@dev-ritik there's a missing comma in the `ImportForm.Media` class. I'll fix it and see if we can get a bugfix release out

**Comment by dev-ritik** [comment]
Thanks @jaap3 for the PR, looking forward to seeing it released in the next update soon :smiley:

**Comment by semente** [comment]
@dev-ritik version 1.0.2 was released in PyPI ;)

**Comment by dev-ritik** [comment]
Thanks for the prompt patch guys! The bug is fixed :smiley:
