### ISSUE TITLE
Incompatible with virtual models

### ISSUE THREAD

**Issue by jayvdb** [semente/django-smuggler#69]
This may be a 'wontfix', but could be worth documenting, ...

I am using https://github.com/idlesign/django-siteprefs which creates virtual models in apps named `app.preferences`.

I am also using django-haystackbrowser

smuggler 'dump' endpoint fails because of these models.

> An exception occurred while dumping data: Unable to serialize database: no such table: haystackbrowser_haystackresults

I can put them `SMUGGLER_EXCLUDE_LIST`, and it may be that is the most appropriate approach.

However if there is no table, there is nothing to dump, and the dump process could skip past these, perhaps leaving a note, maybe in the fixture?

The only other time this will happen is when a real table for a normal model hasnt been created yet, perhaps because a migration hasnt been run.  In which case, the site has bigger problems, and even then, the admin probably would like smuggler to do the dump despite the problem, as they may be trying to rescue a site.  Again in that case the admin could put the broken table into SMUGGLER_EXCLUDE_LIST, but that could require a few more complicated steps to edit that file if the site is deployed on the cloud or a remote locked down host.

**Comment by jaap3** [comment]
What happens when you run `./manage.py dumpdata`? 

In it's core smuggler is just a wrapper for this management command. So if Django fails in this situation as well you should probably report this with `django-siteprefs` (or even file a Django issue).

**Comment by jaap3** [comment]
Seems like it could be related to this ticket in `django-siteprefs`: https://github.com/idlesign/django-siteprefs/issues/21

**Comment by jayvdb** [comment]
No this issue isnt related to that issue.

> What happens when you run ./manage.py dumpdata?

It fails with the same errors.

> In it's core smuggler is just a wrapper for this management command.

The "load" endpoint is a great wrapper.

The "dump" endpoint is not so much.

It would be good if it detects fake models, and/or allows the user to select models to be dumped.

**Comment by jaap3** [comment]
`dumpdata` is a management command from Django core. You might want to file
a ticket on code.djangoproject.com if you think it could work better.
