### ISSUE TITLE
Permission denied in windows, solution explained 

### ISSUE THREAD

**Issue by ManiMozaffar** [semente/django-smuggler#75]
Hello,
In some windows, this bug happens:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

The way to fix it:
https://stackoverflow.com/questions/27215462/permissionerror-winerror-32-the-process-cannot-access-the-file-because-it-is

I'd appreciate devs if they can apply this to the project.

**Comment by jaap3** [comment]
This looks similar to #61, can you confirm it is the same issue?

**Comment by ManiMozaffar** [comment]
Yes it is same.

**Comment by ManiMozaffar** [comment]
The reason is that you are trying to delete the file right after you loaded, before you close!
win32 API will not allow you to do, using SMUGGLER_FIXTURE_DIR and saving the json file helped it to be fixed, please apply this in default setting and everything works great then.

**Comment by semente** [comment]
Hey! Well, lets continue this discussion on #61 so.
